In [2]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [46]:
from proj1_helpers import *

DATA_TRAIN_PATH = "../data/train.csv" # download train data and supply path
y_tr, tX_tr, ids_tr = load_csv_data(DATA_TRAIN_PATH)

DATA_TEST_PATH = "../data/test.csv" #download train data and supply path
y_fin, tX_fin, ids_fin = load_csv_data(DATA_TEST_PATH)

## Implementation

In [20]:
y_tr = np.array([-1, 3, 3, 2])
y_tr = y_tr -1
print(y_tr)

[-2  2  2  1]


In [47]:
from data_analysis import *

##### Data analysis #####

#Separate the data
jet_num = 0
y0_tr, tX0_tr, ids0_tr, y0_fin, tX0_fin, ids0_fin = data_analysis(jet_num, y_tr, tX_tr, ids_tr, y_fin, tX_fin, ids_fin)
jet_num = 1
y1_tr, tX1_tr, ids1_tr, y1_fin, tX1_fin, ids1_fin = data_analysis(jet_num, y_tr, tX_tr, ids_tr, y_fin, tX_fin, ids_fin)
jet_num = 2
y2_tr, tX2_tr, ids2_tr, y2_fin, tX2_fin, ids2_fin = data_analysis(jet_num, y_tr, tX_tr, ids_tr, y_fin, tX_fin, ids_fin)
jet_num = 3
y3_tr, tX3_tr, ids3_tr, y3_fin, tX3_fin, ids3_fin = data_analysis(jet_num, y_tr, tX_tr, ids_tr, y_fin, tX_fin, ids_fin)


In [48]:
# Split the data into train (80%) and test (20%) parts 
ratio = 0.8;
tX0_tr, tX0_te, y0_tr, y0_te, ids0_tr, ids0_te = split_data(tX0_tr, y0_tr, ids0_tr, ratio)
tX1_tr, tX1_te, y1_tr, y1_te, ids1_tr, ids1_te = split_data(tX1_tr, y1_tr, ids1_tr, ratio)
tX2_tr, tX2_te, y2_tr, y2_te, ids2_tr, ids2_te = split_data(tX2_tr, y2_tr, ids2_tr, ratio)
tX3_tr, tX3_te, y3_tr, y3_te, ids3_tr, ids3_te = split_data(tX3_tr, y3_tr, ids3_tr, ratio)

In [49]:
sigma = sigmoid(-0.9432351)
s = np.array([-0.9432351  -0.7698851  -0.95620997])
#sig = 1.0/(1.0 + np.exp(+0.9432351))
sig = 1.0 ./ (1.0 + np.exp(-s))
print(sigma)
print(sig)

SyntaxError: invalid syntax (<ipython-input-49-77b9da20e957>, line 4)

In [55]:
from implementation import *
from optimization import * 

##### Logistic regression #####

lambda_ = 0.15
max_iters = 150
gamma = 0.01

init_w0, _ = least_squares(y0_tr, tX0_tr)
init_w1, _ = least_squares(y1_tr, tX1_tr)
init_w2, _ = least_squares(y2_tr, tX2_tr)
init_w3, _ = least_squares(y3_tr, tX3_tr)

w0, loss0 = logistic_regression(y0_tr, tX0_tr, init_w0, max_iters, gamma)
w1, loss1 = logistic_regression(y1_tr, tX1_tr, init_w1, max_iters, gamma)
w2, loss2 = logistic_regression(y2_tr, tX2_tr, init_w2, max_iters, gamma)
w3, loss3 = logistic_regression(y3_tr, tX3_tr, init_w3, max_iters, gamma)

57359.754843420735
20763224.456857156
15208880.864025151
23807004.610636
15174668.505487073
15174668.505487073
30588079.773816213
28857380.679944035
27567723.512443654
15655872.765794383
16552831.557031741
16813250.4748752
16018821.265067898
21519573.520469483
15174668.505487073
15340011.358614132
28550982.858309407
15174668.505487073
15174668.505487073
18054014.46105274
15174668.505487073
13419096.836267643
26797098.27054366
30565767.366073992
14955166.72236409
15199475.451507255
15080352.483451152
19964536.20278278
15174668.505487073
12452147.522192609
15044191.969972335
15174668.505487073
18909035.542809427
15174668.505487073
12700691.063758776
13608146.418972999
28269608.919103067
30585848.53304199
15675112.543955624
14719839.774440523
16235417.160602765
15267636.871079676
17154020.624758072
15176899.746261295
13061683.492298245
14751710.825122163
25636956.495816436
15174668.505487073
15146406.122346923
21947816.843238246
28735406.184286542
30251162.41690861
14733422.573859008
1464

11920775.709745893
11786901.263292542
11918544.46897167
11786159.368267052
11925888.271102829
11789681.27724408
11925238.191294339
11785413.769443061
13036.553109162784
4005077.189729315
8539702.189874075
4005077.189729315
4005077.189729315
8535983.455250373
4005077.189729315
4005077.189729315
7712473.98607021
4005077.189729315
3868227.7555770045
9076687.46953695
4005077.189729315
3968633.5904170154
8511439.806733925
4005077.189729315
3903927.6079645636
8434833.873485621
4005077.189729315
3892027.657168711
7596631.089302722
4005077.189729315
3845171.600910041
8370127.891033169
4005077.189729315
3904671.354889305
7627868.460141836
4005077.189729315
3824346.687017298
8318809.353226053
4005077.189729315
3882358.9471470807
7437469.247408185
4005077.189729315
3835502.89088841
8106841.4796749195
4005077.189729315
3862277.780179078
7798186.505907482
4005077.189729315
3809471.748522481
7794467.7712837765
4005077.189729315
3805753.0138987764
7758039.568806727
4005077.189729315
3792365.569253442

## Test the implementation:

In [ ]:
def (y, tx, w):
    """compute the cost by negative log likelihood, for logistic regression."""
    pred = sigmoid(tx.dot(w))
    pred[pred<=0.5] = 0;
    pred[pred>0.5] = 1;
    num_fail = np.count_nonzero( y-pred )
    success_rate = 1-num_fail/y.shape[0]
    return success_rate

In [65]:
y0_pred = predict_labels(w0, tX0_te)
y1_pred = predict_labels(w1, tX1_te)
y2_pred = predict_labels(w2, tX2_te)
y3_pred = predict_labels(w3, tX3_te)

y0_pred[y0_pred <= 0.5] = -1
y0_pred[y0_pred > 0.5] = +1

y1_pred[y1_pred <= 0.5] = -1
y1_pred[y1_pred > 0.5] = +1

y2_pred[y2_pred <= 0.5] = -1
y2_pred[y2_pred > 0.5] = +1

y3_pred[y3_pred <= 0.5] = -1
y3_pred[y3_pred > 0.5] = +1

y0_te[y0_te <= 0.5] = -1
y0_te[y0_te > 0.5] = +1

y1_te[y1_te <= 0.5] = -1
y1_te[y1_te > 0.5] = +1

y2_te[y2_te <= 0.5] = -1
y2_te[y2_te > 0.5] = +1

y3_te[y3_te <= 0.5] = -1
y3_te[y3_te > 0.5] = +1



print(y0_pred)
print(y0_te)

grades = [0., 0., 0., 0.]
res0 = np.where(y0_te[:,] == y0_pred[:,], 1, 0)
grades[0] = np.mean(res0)
res1 = np.where(y1_te[:,] == y1_pred[:,], 1, 0)
grades[1] = np.mean(res0)
res2 = np.where(y2_te[:,] == y2_pred[:,], 1, 0)
grades[2] = np.mean(res2)
res3 = np.where(y3_te[:,] == y3_pred[:,], 1, 0)
grades[3] = np.mean(res3)
grade = np.mean(grades)


[-1. -1. -1. ... -1. -1.  1.]
[-1. -1. -1. ...  1.  1.  1.]


In [64]:
print(grade)

0.7335973676325374


## Generate predictions and save ouput in csv format for submission:

In [11]:
y0_pred = predict_labels(w0, tX0_fin)
y1_pred = predict_labels(w1, tX1_fin)
y2_pred = predict_labels(w2, tX2_fin)
y3_pred = predict_labels(w3, tX3_fin)

In [12]:
y_pred = np.concatenate([y0_pred, y1_pred, y2_pred, y3_pred])
ids_pred = np.concatenate([ids0_te, ids1_te, ids2_te, ids3_te])
OUTPUT_PATH = 'results_ridge.csv' 
create_csv_submission(ids_pred, y_pred, OUTPUT_PATH)