In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [2]:
from proj1_helpers import *

DATA_TRAIN_PATH = "data/train.csv" # download train data and supply path
y_tr, tX_tr, ids_tr = load_csv_data(DATA_TRAIN_PATH)

DATA_TEST_PATH = "data/test.csv" #download train data and supply path
y_fin, tX_fin, ids_fin = load_csv_data(DATA_TEST_PATH)

## Implementation

In [3]:
from data_analysis import * 

# Split the data into train (80%) and test (20%) parts 
ratio = 0.8;
tX_tr, tX_te, y_tr, y_te, ids_tr, ids_te = split_data(tX_tr, y_tr, ids_tr, ratio)

In [4]:
from data_analysis import *

##### Data analysis #####

#Separate the data
jet_num = 0
y0_tr, tX0_tr, ids0_tr, y0_te, tX0_te, ids0_te, y0_fin, tX0_fin, ids0_fin = data_analysis(jet_num, y_tr, tX_tr, ids_tr, y_te, tX_te, ids_te, y_fin, tX_fin, ids_fin)
jet_num = 1
y1_tr, tX1_tr, ids1_tr, y1_te, tX1_te, ids1_te, y1_fin, tX1_fin, ids1_fin = data_analysis(jet_num, y_tr, tX_tr, ids_tr, y_te, tX_te, ids_te, y_fin, tX_fin, ids_fin)
jet_num = 2
y2_tr, tX2_tr, ids2_tr, y2_te, tX2_te, ids2_te, y2_fin, tX2_fin, ids2_fin = data_analysis(jet_num, y_tr, tX_tr, ids_tr, y_te, tX_te, ids_te, y_fin, tX_fin, ids_fin)
jet_num = 3
y3_tr, tX3_tr, ids3_tr, y3_te, tX3_te, ids3_te, y3_fin, tX3_fin, ids3_fin = data_analysis(jet_num, y_tr, tX_tr, ids_tr, y_te, tX_te, ids_te, y_fin, tX_fin, ids_fin)


In [23]:
from implementation import *
from optimization import * 

##### TRAINING #####
##### Cross validation #####

best_lambdas = [0., 0., 0., 0.,]
deg0 = np.ones(tX0_tr.shape[1],np.int64)
feat_ind = 1

best_lambdas[0] = cross_validation_degree(y0_tr, tX0_tr, feat_ind, deg0)
print(best_lambdas[0])

#best_lambdas[1] = cross_validation_degree(y1_tr, tX1_tr, feat_ind, expansion_degrees)
#print(best_lambdas[1])

#best_lambdas[2] = cross_validation_degree(y2_tr, tX2_tr, feat_ind, expansion_degrees)
#print(best_lambdas[2])

#best_lambdas[3] = cross_validation_degree(y3_tr, tX3_tr, feat_ind, expansion_degrees)
#print(best_lambdas[3])


 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
 x size (79922, 18)
--feat_ind 1 , degree 1 , fold 0
[61285 37945 74462 ... 21440 73349 50057]
(59940,)
(79922, 19)
--feat_ind 1 , degree 1 , fold 1
[78190 79505 62082 ... 21440 73349 50057]
(59940,)
(79922, 19)
--feat_ind 1 , degree 1 , fold 2
[78190 79505 62082 ... 21440 73349 50057]
(59940,)
(79922, 19)
--feat_ind 1 , degree 1 , fold 3
[78190 79505 62082 ... 44147 72558 77820]
(59940,)
(79922, 19)
 x size (79922, 19)


IndexError: index 18 is out of bounds for axis 0 with size 18

In [8]:
#best_lambdas = [100, 100, 100, 100]

##### Ridge regression #####

w0, loss0 = ridge_regression(y0_tr, tX0_tr, best_lambdas[0])
w1, loss1 = ridge_regression(y1_tr, tX1_tr, best_lambdas[1])
w2, loss2 = ridge_regression(y2_tr, tX2_tr, best_lambdas[2])
w3, loss3 = ridge_regression(y3_tr, tX3_tr, best_lambdas[3])

In [9]:
print(best_lambdas)

[0.27185882427329455, 3.0538555088334185, 7.564633275546306, 34.30469286314926]


## Test the implementation:

In [10]:
##### TESTING #####

y0_pred = predict_labels(w0, tX0_te)
y1_pred = predict_labels(w1, tX1_te)
y2_pred = predict_labels(w2, tX2_te)
y3_pred = predict_labels(w3, tX3_te)

print(y0_pred.shape)
print(y0_te.shape)

grades = [0., 0., 0., 0.]
res0 = np.where(y0_te[:,] == y0_pred[:,], 1, 0)
grades[0] = np.mean(res0)
res1 = np.where(y1_te[:,] == y1_pred[:,], 1, 0)
grades[1] = np.mean(res0)
res2 = np.where(y2_te[:,] == y2_pred[:,], 1, 0)
grades[2] = np.mean(res2)
res3 = np.where(y3_te[:,] == y3_pred[:,], 1, 0)
grades[3] = np.mean(res3)
grade = np.mean(grades)


(19990,)
(19990,)


In [11]:
print(grade)

0.7667287784810132


## Generate predictions and save ouput in csv format for submission:

In [15]:
y0_pred = predict_labels(w0, tX0_fin)
y1_pred = predict_labels(w1, tX1_fin)
y2_pred = predict_labels(w2, tX2_fin)
y3_pred = predict_labels(w3, tX3_fin)

In [16]:
y_pred = np.concatenate([y0_pred, y1_pred, y2_pred, y3_pred])
ids_pred = np.concatenate([ids0_te, ids1_te, ids2_te, ids3_te])
OUTPUT_PATH = 'data/results_ridge_cross_validation.csv' 
create_csv_submission(ids_pred, y_pred, OUTPUT_PATH)

In [ ]:
"Result : 0. ..."