In [14]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [30]:
from proj1_helpers import *
from data_analysis_logistic import *
from optimization import*
from implementation import *

In [31]:
DATA_TRAIN_PATH = "data/train.csv" # download train data and supply path
y_tr, tX_tr, ids_tr = load_csv_data(DATA_TRAIN_PATH)

DATA_TEST_PATH = "data/test.csv" #download train data and supply path
y_fin, tX_fin, ids_fin = load_csv_data(DATA_TEST_PATH)

# Implementation

## Separation of the data

In [32]:

jet_num = 0
y0_tr, tX0_tr, ids0_tr, y0_te, tX0_te, ids0_te, y0_fin, tX0_fin, ids0_fin = data_analysis(jet_num, y_tr, tX_tr, ids_tr, y_fin, tX_fin, ids_fin)
jet_num = 1
y1_tr, tX1_tr, ids1_tr,y1_te, tX1_te, ids1_te, y1_fin, tX1_fin, ids1_fin = data_analysis(jet_num, y_tr, tX_tr, ids_tr, y_fin, tX_fin, ids_fin)
jet_num = 2
y2_tr, tX2_tr, ids2_tr,y2_te, tX2_te, ids2_te, y2_fin, tX2_fin, ids2_fin = data_analysis(jet_num, y_tr, tX_tr, ids_tr, y_fin, tX_fin, ids_fin)
jet_num = 3
y3_tr, tX3_tr, ids3_tr,y3_te, tX3_te, ids3_te, y3_fin, tX3_fin, ids3_fin = data_analysis(jet_num, y_tr, tX_tr, ids_tr, y_fin, tX_fin, ids_fin)


In [33]:


##### Logistic regression #####

max_iters = 150
#gamma=0.00028072162039411786
gamma=0.01


w0, loss0 = logistic_regression(y0_tr, tX0_tr, max_iters, gamma)
w1, loss1 = logistic_regression(y1_tr, tX1_tr, max_iters, gamma)
w2, loss2 = logistic_regression(y2_tr, tX2_tr, max_iters, gamma)
w3, loss3 = logistic_regression(y3_tr, tX3_tr, max_iters, gamma)


## Test degree

Dans best_degree_logistic_regression, nous considérons que les degrées entre chaques paramètres sont indépendant entre eux.

In [35]:
deg0=best_degree_logistic_regression(tX0_te, tX0_tr, y0_tr,y0_te)
deg1=best_degree_logistic_regression(tX1_te, tX1_tr, y1_tr,y1_te)
deg2=best_degree_logistic_regression(tX2_te, tX2_tr, y2_tr,y2_te)
deg3=best_degree_logistic_regression(tX3_te, tX3_tr, y3_tr,y3_te)

In [36]:
print(deg0)
print(deg1)
print(deg2)
print(deg3)

[1 1 2 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1]
[1 3 4 1 4 1 3 1 6 1 1 3 9 1 1 1 1 1 1 1]
[1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 4 1 1 1 1 1 1 1 1 1 1 1 1 1 7 1 1 1 1 1 1 1 1 1]


In [37]:
tX0_tr,tX0_te,tX0_fin= build_poly_data(tX0_tr,tX0_te,tX0_fin,deg0)
tX1_tr,tX1_te,tX1_fin= build_poly_data(tX1_tr,tX1_te,tX1_fin,deg1)
tX2_tr,tX2_te,tX2_fin= build_poly_data(tX2_tr,tX2_te,tX2_fin,deg2)
tX3_tr,tX3_te,tX3_fin= build_poly_data(tX3_tr,tX3_te,tX3_fin,deg3)

In [48]:
print(deg0)
max_iters = 50
#gamma=0.00028072162039411786
gamma=0.01


w0, loss0 = logistic_regression(y0_tr, tX0_tr, max_iters, gamma)
w1, loss1 = logistic_regression(y1_tr, tX1_tr, max_iters, gamma)
w2, loss2 = logistic_regression(y2_tr, tX2_tr, max_iters, gamma)
w3, loss3 = logistic_regression(y3_tr, tX3_tr, max_iters, gamma)

[1 1 2 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1]


## Test the implementation:

In [49]:
y0_pred = predict_labels(w0, tX0_te)
y1_pred = predict_labels(w1, tX1_te)
y2_pred = predict_labels(w2, tX2_te)
y3_pred = predict_labels(w3, tX3_te)


grades = [0., 0., 0., 0.]
res0 = np.where(y0_te[:,] == y0_pred[:,], 1, 0)
grades[0] = np.mean(res0)
res1 = np.where(y1_te[:,] == y1_pred[:,], 1, 0)
grades[1] = np.mean(res0)
res2 = np.where(y2_te[:,] == y2_pred[:,], 1, 0)
grades[2] = np.mean(res2)
res3 = np.where(y3_te[:,] == y3_pred[:,], 1, 0)
grades[3] = np.mean(res3)
grade = np.mean(grades)

In [50]:
print(grade)

0.764904408279075


## Generate predictions and save ouput in csv format for submission:

In [51]:
y0_pred = predict_labels(w0, tX0_fin)
y1_pred = predict_labels(w1, tX1_fin)
y2_pred = predict_labels(w2, tX2_fin)
y3_pred = predict_labels(w3, tX3_fin)

In [52]:
y_pred = np.concatenate([y0_pred, y1_pred, y2_pred, y3_pred])
print(y_pred.shape)
ids_pred = np.concatenate([ids0_fin, ids1_fin, ids2_fin, ids3_fin])
print(ids_pred.shape)
OUTPUT_PATH = 'results_logistic.csv' 
create_csv_submission(ids_pred, y_pred, OUTPUT_PATH)

(568238,)
(568238,)
